# Generated by Django 2.0 on 2018-11-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('biografia', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('año', models.IntegerField()),
                ('resumen', models.CharField(max_length=500)),
                ('categoria', models.CharField(choices=[('UK', 'unknown'), ('AC', 'Action'), ('AD', 'Adventure'), ('AN', 'Animation'), ('CH', "Children's"), ('CO', 'Comedy'), ('CR', 'Crime'), ('DO', 'Documentar'), ('DR', 'Drama'), ('FA', 'Fantasy'), ('FN', 'Film-Noir'), ('HR', 'Horror'), ('MS', 'Musical'), ('MY', 'Mystery'), ('RO', 'Romance'), ('SF', 'Sci-Fi'), ('TH', 'Thriller'), ('W', 'War'), ('WS', 'Western')], max_length=200)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica.Director')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('fechaNacimiento', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('categoria', models.CharField(choices=[('UK', 'unknown'), ('AC', 'Action'), ('AD', 'Adventure'), ('AN', 'Animation'), ('CH', "Children's"), ('CO', 'Comedy'), ('CR', 'Crime'), ('DO', 'Documentar'), ('DR', 'Drama'), ('FA', 'Fantasy'), ('FN', 'Film-Noir'), ('HR', 'Horror'), ('MS', 'Musical'), ('MY', 'Mystery'), ('RO', 'Romance'), ('SF', 'Sci-Fi'), ('TH', 'Thriller'), ('W', 'War'), ('WS', 'Western')], max_length=200)),
            ],
        ),
    ]
